### ISSUE TITLE
`tokenizer` seems to be broken

### ISSUE THREAD

**Issue by sarbbottam** [thejameskyle/the-super-tiny-compiler#25]
```
吽 git lol | head -2
* 93572fe (HEAD -> master, upstream/master, origin/master, origin/HEAD) Update README.md
* 974ca6a Delete super-tiny-compiler-unannotated.js
[zsh] sabandyo at sabandyo-mn1 in ~/GitHub/the-super-tiny-compiler (master)
吽 node test.js     
/Users/sabandyo/GitHub/the-super-tiny-compiler/super-tiny-compiler.js:471
    throw new TypeError('I dont know what this character is: ' + char);
          ^
TypeError: I dont know what this character is: a
    at tokenizer (/Users/sabandyo/GitHub/the-super-tiny-compiler/super-tiny-compiler.js:471:11)
    at Object.<anonymous> (/Users/sabandyo/GitHub/the-super-tiny-compiler/test.js:78:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by sarbbottam** [comment]
[my commit](https://github.com/thejameskyle/the-super-tiny-compiler/commit/4efa9f85227f9f8d9c39c9503c01f9eac0d92f8a) seems to be the culprit
