### ISSUE TITLE
assert.deepStrictEqual should be assert.deepEqual

### ISSUE THREAD

**Issue by sarbbottam** [thejameskyle/the-super-tiny-compiler#26]
```
assert.deepStrictEqual(tokenizer(input), tokens, 'Tokenizer should turn `input
       ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/sabandyo/GitHub/the-super-tiny-compiler/test.js:78:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by sarbbottam** [comment]
`deepStrictEqual` is not available in node 0.12.x but in higher version.
