### ISSUE TITLE
Error: assert.deepStrictEqual(tokenizer(input), tokens, 'Tokenizer should turn `input

### ISSUE THREAD

**Issue by 1c7** [thejameskyle/the-super-tiny-compiler#40]
![image](https://cloud.githubusercontent.com/assets/1804755/14630049/93401ca8-063d-11e6-8de0-0336c2e8a44f.png)

```
/home/a/Desktop/the-super-tiny-compiler/test.js:78
assert.deepStrictEqual(tokenizer(input), tokens, 'Tokenizer should turn `input
       ^
TypeError: Object function ok(value, message) {
  if (!!!value) fail(value, true, message, '==', assert.ok);
} has no method 'deepStrictEqual'
    at Object.<anonymous> (/home/a/Desktop/the-super-tiny-compiler/test.js:78:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Not sure why. but it's not wokring

Env:
   Ubuntu 14.04 LTS
  NodeJS: v0.10.25

**Comment by 1c7** [comment]
Seem like NodeJS version problem.
updating nodejs. I will be back.

**Comment by 1c7** [comment]
Problem confirm: NodeJS version cause this.
NodeJS 5.10.1  totally work
![image](https://cloud.githubusercontent.com/assets/1804755/14634054/de4dada4-0652-11e6-8dbd-02ea8c41ea61.png)
